Repository sakisandrac/rancid-tomatillos-paired, pull requests merged in 2023-07, with the labels that each got.

#9 Ch/feature/apicalls
  src/apiCalls/apiCalls.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/Homepage/Homepage.css
  src/components/Homepage/Homepage.js
  src/mock-data/mock-movies.js
Labels: documentation, feature

#11 Add proptypes to each component
  package-lock.json
  package.json
  src/apiCalls/apiCalls.js
  src/components/Homepage/Homepage.js
  src/components/MovieDetails/MovieDetails.js
  src/components/MoviePoster/MoviePoster.js
Labels: enhancement

#12 Ch/style/movie details
  src/apiCalls/apiCalls.js
  src/components/Homepage/Homepage.css
  src/components/Homepage/Homepage.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
Labels: enhancement, help wanted

#13 Sc/feature/add styling deatils
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
Labels: enhancement

#14 Fix proptype and styling for movie details
  src/components/Homepage/Homepage.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
Labels: enhancement

#18 Sc/cypress/moviedetails
  cypress.config.js
  cypress/e2e/moviedetails_spec.cy.js
  cypress/fixtures/moviedetails.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: testing

#19 Sc/feature/router
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/Homepage/Homepage.css
  src/components/Homepage/Homepage.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/components/MoviePoster/MoviePoster.js
  src/index.js
  src/reportWebVitals.js
Labels: enhancement

#22 Sc/refactor/testing movie details
  cypress/e2e/homepage_spec.cy.js
  cypress/e2e/moviedetails_spec.cy.js
  src/components/Homepage/Homepage.js
  src/components/MovieDetails/MovieDetails.js
Labels: enhancement

#24 Sc/feature/search
  src/components/App/App.js
  src/components/Homepage/Homepage.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
  src/components/SearchResults/SearchResults.js
Labels: feature

#25 Ch/feature/search
  cypress/e2e/homepage_spec.cy.js
  src/components/App/App.js
  src/components/Homepage/Homepage.css
  src/components/Homepage/Homepage.js
  src/components/MovieDetails/MovieDetails.css
  src/components/MovieDetails/MovieDetails.js
  src/components/MoviePoster/MoviePoster.css
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
  src/components/NavBar/small-logo.png
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/components/Search/search-symbol.png
  src/components/SearchResults/SearchResults.css
  src/components/SearchResults/SearchResults.js
Labels: enhancement

#26 Ch/cypress/searchresults
  cypress/e2e/homepage_spec.cy.js
  cypress/e2e/searchresults_spec.cy.js
  cypress/support/e2e.js
  src/components/Homepage/Homepage.css
  src/components/Homepage/Homepage.js
  src/components/NavBar/NavBar.js
Labels: enhancement, testing

#28 Ch/refactor/cypress
  cypress/e2e/errorhandling_spec.cy.js
  cypress/e2e/homepage_spec.cy.js
Labels: testing

#30 Update README.md
  README.md
Labels: documentation
